//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rorepairadminEntities : DbContext
    {
        public rorepairadminEntities()
            : base("name=rorepairadminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<tbl_blogs> tbl_blogs { get; set; }
        public virtual DbSet<tbl_customerreviews> tbl_customerreviews { get; set; }
        public virtual DbSet<tbl_faqs> tbl_faqs { get; set; }
        public virtual DbSet<tbl_headers> tbl_headers { get; set; }
        public virtual DbSet<tbl_howitworks> tbl_howitworks { get; set; }
        public virtual DbSet<tbl_techanicians> tbl_techanicians { get; set; }
    }
}
