//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_headers
    {
        public int headerid { get; set; }
        public string technicianheader { get; set; }
        public string customerreviewsheader { get; set; }
        public string blogheader { get; set; }
        public string faqsheader { get; set; }
        public string aboutrorepairheader { get; set; }
        public string avgrating { get; set; }
        public Nullable<int> totalnoofratings { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
