//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_howitworks
    {
        public int howitworksid { get; set; }
        public string howitworksheader { get; set; }
        public string howitworksiconone { get; set; }
        public string howitworkssubheaderone { get; set; }
        public string howitworksparaone { get; set; }
        public string howitworksicontwo { get; set; }
        public string howitworkssubheadertwo { get; set; }
        public string howitworksparatwo { get; set; }
        public string howitworksiconthree { get; set; }
        public string howitworkssubheaderthree { get; set; }
        public string howitworksparathree { get; set; }
        public string howitworksiconfour { get; set; }
        public string howitworkssubheaderfour { get; set; }
        public string howitworksparafour { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
