//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerreviews
    {
        public int customerreviewsid { get; set; }
        public Nullable<int> technicianid { get; set; }
        public string customername { get; set; }
        public string rating { get; set; }
        public string monthandyear { get; set; }
        public string comments { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
