//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_techanicians
    {
        public int technicianid { get; set; }
        public string technicianname { get; set; }
        public string technicianaddress { get; set; }
        public string technicianavgrating { get; set; }
        public Nullable<int> techniciantotalnorating { get; set; }
        public string technicianimage { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
