//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blogs
    {
        public int blogid { get; set; }
        public string blogname { get; set; }
        public string blogimage { get; set; }
        public string blogdate { get; set; }
        public string blogdesc { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
