//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoRepairAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faqs
    {
        public int faqid { get; set; }
        public string faqquestion { get; set; }
        public string faqanswer { get; set; }
        public Nullable<int> Cityid { get; set; }
    }
}
